apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: 5xjujh85c-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: 5xjujh85c-go 
  name: 5xjujh85c-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: 5xjujh85c-go 
